spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: plan-service
          uri: http://localhost:8083
          predicates:
            - Path=/plans/**
        - id: task-service
          uri: http://localhost:8084
          predicates:
            - Path=/tasks/**
server:
  port: 8080
